# Generated by Django 4.2.30 on 2026-06-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users_login_new',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterField(
            model_name='users_login_new',
            name='Role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='users_login_new',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='users_login_new_groups', to='auth.group', verbose_name='المجموعات'),
        ),
        migrations.AlterField(
            model_name='users_login_new',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='users_login_new_permissions', to='auth.permission', verbose_name='أذونات المستخدم'),
        ),
    ]
